import sys
import pathlib
current_dir = pathlib.Path(__file__).resolve().parent
sys.path.append( str(current_dir) + '/../' )
from aseInterface import *
from ase.build import bulk, make_supercell
from ase.optimize import BFGS
from ase.io import read, write
from ase.io.trajectory import Trajectory

hdnnpy=hdnnpy()
#please specify the prefix used in hdnnpy training
hdnnpy.set_label('./Crystal')

#sample: one atom has 0.03A displacement. one of the displacements patterns generated by phono3py
dist = read('POSCAR-00046',format='vasp')
print(dist)
dist.set_calculator(hdnnpy)
e=dist.get_potential_energy()
print(e)
f=dist.get_forces()
print(f)
dyn=BFGS(dist, trajectory='Si.traj', logfile='Si.log')
dyn.run(fmax=0.05)

#extract initial and final coordinate
traj=Trajectory('Si.traj')

initial=traj[0]
final=traj[-1]

write('initial-dyn.xyz',initial)
write('final-dyn.xyz',final)

